@echo off
setlocal
:: 设置控制台为 UTF-8 编码，防止中文乱码
chcp 65001 >nul
title OpenWrt 自动认证脚本生成器
color 0A

echo ========================================================
echo       OpenWrt/Kwrt 自动认证脚本生成器 v1.1
echo ========================================================
echo.
echo  此工具将帮助你生成带有自动 Curl 认证功能的 Watchdog 脚本。
echo  它会自动将 Curl 命令中的静态 IP 替换为路由器的动态 IP 变量。
echo.

:: --- 1. 获取用户输入 ---

set /p LOGICAL_IF="1. 请输入逻辑接口名称 (默认 wwan): "
if "%LOGICAL_IF%"=="" set LOGICAL_IF=wwan

set /p PHYSICAL_IF="2. 请输入物理接口名称 (ifconfig能看到IP的那个，如 phy0-sta0): "
if "%PHYSICAL_IF%"=="" set PHYSICAL_IF=phy0-sta0

echo.
echo --------------------------------------------------------
echo 3. 请粘贴你抓取到的完整 Curl 命令 (Copy as cURL Bash):
echo    (粘贴后直接按回车，如果有多行请一次性粘贴)
echo --------------------------------------------------------
set /p RAW_CURL=

echo.
echo --------------------------------------------------------
echo 4. 请输入该 Curl 命令中包含的旧 IP 地址:
echo    (脚本需要知道哪个是旧IP，才能用 ${CURRENT_IP} 替换它)
echo    例如抓包里看到的是 10.100.1.5，就输 10.100.1.5
echo --------------------------------------------------------
set /p OLD_IP=

echo.
echo --------------------------------------------------------
echo 5. 请输入该 Curl 命令中包含的旧 MAC 地址 (选填):
echo    (如果不填，则直接回车跳过 MAC 地址替换)
echo --------------------------------------------------------
set /p OLD_MAC=

echo.
echo 正在生成 network_watchdog.sh ...

:: --- 2. 生成 PowerShell 处理脚本 (解决特殊字符问题) ---
set "PS_SCRIPT=generate_temp.ps1"

:: 将用户输入写入 PS 脚本变量 (使用 @' ... '@ 语法避免转义)
echo $curl = @' > %PS_SCRIPT%
echo %RAW_CURL% >> %PS_SCRIPT%
echo '@ >> %PS_SCRIPT%

echo $old_ip = '%OLD_IP%' >> %PS_SCRIPT%
echo $old_mac = '%OLD_MAC%' >> %PS_SCRIPT%
echo $logical_if = '%LOGICAL_IF%' >> %PS_SCRIPT%
echo $physical_if = '%PHYSICAL_IF%' >> %PS_SCRIPT%

:: 写入 Shell 脚本模板到 PS 变量
echo $template = @' >> %PS_SCRIPT%
echo #!/bin/sh >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # ========================================================= >> %PS_SCRIPT%
echo # OpenWrt 自动认证看门狗 (Generated by Tool) >> %PS_SCRIPT%
echo # ========================================================= >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # --- 配置区域 --- >> %PS_SCRIPT%
echo TARGET_IP="223.5.5.5" >> %PS_SCRIPT%
echo LOGICAL_IF="LOGICAL_IF_PLACEHOLDER" >> %PS_SCRIPT%
echo PHYSICAL_IF="PHYSICAL_IF_PLACEHOLDER" >> %PS_SCRIPT%
echo LOG_TAG="Network_Watchdog" >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # --- 核心逻辑 --- >> %PS_SCRIPT%
echo if ping -c 3 -W 10 $TARGET_IP ^> /dev/null 2^>^&1; then >> %PS_SCRIPT%
echo     exit 0 >> %PS_SCRIPT%
echo else >> %PS_SCRIPT%
echo     logger -t "$LOG_TAG" "检测到网络断开，开始重连..." >> %PS_SCRIPT%
echo     ifup $LOGICAL_IF >> %PS_SCRIPT%
echo     sleep 25 >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo     CURRENT_IP=$(ifconfig $PHYSICAL_IF ^| grep 'inet addr' ^| cut -d: -f2 ^| awk '{print $1}') >> %PS_SCRIPT%
echo     CURRENT_MAC=$(cat /sys/class/net/$PHYSICAL_IF/address) >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo     if [ -z "$CURRENT_IP" ]; then >> %PS_SCRIPT%
echo         logger -t "$LOG_TAG" "错误：物理接口 $PHYSICAL_IF 未获取到IP，放弃认证。" >> %PS_SCRIPT%
echo         exit 1 >> %PS_SCRIPT%
echo     fi >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo     logger -t "$LOG_TAG" "获取新IP: $CURRENT_IP, 发送认证..." >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo     # --- CURL 认证命令 --- >> %PS_SCRIPT%
echo     CURL_COMMAND_PLACEHOLDER >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo     logger -t "$LOG_TAG" "认证请求已发送。" >> %PS_SCRIPT%
echo fi >> %PS_SCRIPT%
echo '@ >> %PS_SCRIPT%

:: --- 3. 执行字符串替换逻辑 (PowerShell) ---
echo. >> %PS_SCRIPT%
echo # 替换 IP 和 MAC >> %PS_SCRIPT%
echo $final_curl = $curl.Replace($old_ip, '${CURRENT_IP}') >> %PS_SCRIPT%
echo if ($old_mac -ne "") { $final_curl = $final_curl.Replace($old_mac, '${CURRENT_MAC}') } >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # 确保 Curl 静默运行并追加到模板 >> %PS_SCRIPT%
echo $final_curl = $final_curl + " > /dev/null 2>&1" >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # 替换模板中的占位符 >> %PS_SCRIPT%
echo $output = $template.Replace("LOGICAL_IF_PLACEHOLDER", $logical_if) >> %PS_SCRIPT%
echo $output = $output.Replace("PHYSICAL_IF_PLACEHOLDER", $physical_if) >> %PS_SCRIPT%
echo $output = $output.Replace("CURL_COMMAND_PLACEHOLDER", $final_curl) >> %PS_SCRIPT%
echo. >> %PS_SCRIPT%
echo # 保存文件 (强制使用 Linux 换行符 LF，防止报错) >> %PS_SCRIPT%
echo $output = $output -replace "`r`n", "`n" >> %PS_SCRIPT%
echo [IO.File]::WriteAllText("network_watchdog.sh", $output, [System.Text.Encoding]::UTF8) >> %PS_SCRIPT%

:: --- 4. 运行 PowerShell 并清理 ---
powershell -NoProfile -ExecutionPolicy Bypass -File %PS_SCRIPT%
del %PS_SCRIPT%

echo.
echo ========================================================
echo  成功！脚本已生成为: network_watchdog.sh
echo  文件位于当前目录下。
echo ========================================================
echo.
pause